### ISSUE TITLE
Bugs when evaluation on Codalab

### ISSUE THREAD

**Issue by lezhang7** [Wangt-CN/EqBen#3]
When submitting results, i got this error and failed to get the results
```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpxxlkq6/run/program/evaluate.py", line 38, in 
    submission_score = np.load(submission_score_file)
  File "/opt/conda/lib/python3.9/site-packages/numpy/lib/npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpxxlkq6/run/input/res/prediction.npy'
```

**Comment by Wangt-CN** [comment]
Hi @lezhang7, thanks a lot for your interests. It seemed that it is the issue related to the codalab its own accidentally. Could you pls try to launch the evaluation again?

**Comment by lezhang7** [comment]
it's not , still the same problem tested just right npw
```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpCIPA5T/run/program/evaluate.py", line 38, in 
    submission_score = np.load(submission_score_file)
  File "/opt/conda/lib/python3.9/site-packages/numpy/lib/npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpCIPA5T/run/input/res/prediction.npy'
```
